import { jsPDF } from "jspdf";
import type { PredictionHistoryEntry } from "../types/prediction";

const PROJECT_TITLE = "Pancreatic Cancer Risk Assessment — Report";

function disclaimerLines(): string[] {
  return [
    "MEDICAL DISCLAIMER",
    "This report is generated by a research / educational software demonstration.",
    "It does not constitute medical advice, diagnosis, or treatment.",
    "Consult a qualified healthcare professional for all clinical decisions.",
  ];
}

/**
 * Builds a simple multi-page PDF with inputs, model output, and disclaimer.
 */
export function exportPredictionPdf(entry: PredictionHistoryEntry): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  let y = margin;
  const line = (text: string, size = 11, bold = false) => {
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text, 515);
    doc.text(lines, margin, y);
    y += lines.length * (size * 1.2);
    if (y > 750) {
      doc.addPage();
      y = margin;
    }
  };

  line(PROJECT_TITLE, 16, true);
  y += 8;
  line(`Generated: ${new Date(entry.createdAt).toLocaleString()}`, 10);
  y += 16;

  line("Patient inputs", 13, true);
  y += 4;
  const f = entry.features;
  line(`Age: ${f.age}`, 11);
  line(`Sex: ${f.sex}`, 11);
  line(`Plasma CA19-9: ${f.plasma_CA19_9}`, 11);
  line(`Creatinine: ${f.creatinine}`, 11);
  line(`LYVE1: ${f.LYVE1}`, 11);
  line(`REG1B: ${f.REG1B}`, 11);
  line(`TFF1: ${f.TFF1}`, 11);
  y += 12;

  const r = entry.result;
  line("Prediction result", 13, true);
  y += 4;
  line(`Outcome (class): ${r.prediction} (${r.predicted_label})`, 11);
  line(
    `Probability (PDAC): ${r.probability != null ? (r.probability * 100).toFixed(2) + "%" : "n/a"}`,
    11,
  );
  line(`Risk level: ${r.prediction === 1 ? "High risk signal" : "Low risk signal"}`, 11);
  line(`Model: ${r.model_name} (${r.model_used})`, 11);
  y += 8;
  line(`Message: ${r.message}`, 10);
  y += 16;

  line("Recommendation", 13, true);
  y += 4;
  line(
    r.prediction === 1
      ? "Discuss with a clinician; do not self-diagnose based on this tool alone."
      : "Continue routine care as directed by your physician; this result is not definitive.",
    11,
  );
  y += 20;

  disclaimerLines().forEach((d) => {
    line(d, d.startsWith("MEDICAL") ? 12 : 10, d.startsWith("MEDICAL"));
    y += 4;
  });

  doc.save(`pdac-risk-report-${entry.id.slice(0, 8)}.pdf`);
}
